name: BVault
version: '${project.version}'
main: org.by1337.bvault.core.BVaultCore
api-version: '1.16'
depend: [ BLib, PlaceholderAPI ]
authors: [ By1337 ]

softdepend:
  - Vault

commands:
  bvault:
    permission: bvault.use
    aliases:
      - bv

permissions:
  bvault.*:
    default: op